name: prod-test-task

networks:
  prod-test-task-network:

services:
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
    container_name: prod-test-task-postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - prod-test-task-network

  backend:
    build:
      context: .
      target: prod
    container_name: prod-test-task-backend
    env_file:
      - .env.prod
      - ../secrets.env
    ports:
      - "0.0.0.0:$PORT:$PORT"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - prod-test-task-network
